### ISSUE TITLE
Шилд для одноплатников. not work

### ISSUE THREAD

**Issue by corogoo** [egony/cc2652p_E72-2G4M20S1E#7]
> zigbee2mqtt@1.17.0 start /app

> node index.js

Zigbee2MQTT:info  2021-02-01 01:12:42: Logging to console and directory: '/app/data/log/2021-02-01.01-12-39' filename: log.txt

Zigbee2MQTT:info  2021-02-01 01:12:42: Starting Zigbee2MQTT version 1.17.0 (commit #07cdc9d)

Zigbee2MQTT:info  2021-02-01 01:12:42: Starting zigbee-herdsman (0.13.46)

Zigbee2MQTT:error 2021-02-01 01:13:02: Error while starting zigbee-herdsman

Zigbee2MQTT:error 2021-02-01 01:13:02: Failed to start zigbee

Zigbee2MQTT:error 2021-02-01 01:13:02: Exiting...

Zigbee2MQTT:error 2021-02-01 01:13:02: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)

    at Generator.throw (<anonymous>)

    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! zigbee2mqtt@1.17.0 start: `node index.js`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2021-01-31T17_13_02_811Z-debug.log

**Comment by corogoo** [comment]
serial:
  port: /dev/ttyAMA0

/boot/config.txt  
  enable_uart=1
  dtoverlay=pi3-disable-bt
